// Adapté de l'essai sur la mise en page de texte et pretext

export const BODY_TEXT = `Le web affiche du texte à travers un pipeline conçu il y a trente ans pour des documents statiques. Un navigateur charge une police, façonne le texte en glyphes, mesure leur largeur combinée, détermine où les lignes se coupent, et positionne chaque ligne verticalement. Chaque étape dépend de la précédente. Chaque étape exige que le moteur de rendu consulte son arbre de mise en page interne — une structure si coûteuse à maintenir que les navigateurs en protègent l'accès derrière des barrières de reflow synchrone qui peuvent geler le thread principal pendant des dizaines de millisecondes à la fois.

Pour un paragraphe dans un article de blog, ce pipeline est invisible. Le navigateur charge, met en page et peint avant que l'œil du lecteur n'ait voyagé de la barre d'adresse au premier mot. Mais le web n'est plus une collection de documents statiques. C'est une plateforme pour des applications, et ces applications ont besoin de connaître le texte d'une manière que le pipeline original n'avait jamais anticipée.

Une application de messagerie doit connaître la hauteur exacte de chaque bulle de message avant de rendre une liste virtualisée. Une mise en page en maçonnerie a besoin de la hauteur de chaque carte pour les positionner sans chevauchement. Une page éditoriale doit faire couler le texte autour d'images, de publicités et d'éléments interactifs. Un tableau de bord réactif doit redimensionner et redistribuer le texte en temps réel lorsque l'utilisateur fait glisser un séparateur de panneau.

Chacune de ces opérations nécessite une mesure de texte. Et chaque mesure de texte sur le web aujourd'hui nécessite un reflow de mise en page synchrone. Le coût est dévastateur. Mesurer la hauteur d'un seul bloc de texte oblige le navigateur à recalculer la position de chaque élément de la page. Quand vous mesurez cinq cents blocs de texte en séquence, vous déclenchez cinq cents passes de mise en page complètes. Ce schéma, connu sous le nom de layout thrashing, est la plus grande source de saccades sur le web moderne.

Chrome DevTools le signalera avec des barres rouges furieuses. Lighthouse baissera votre score de performance. Mais le développeur n'a pas d'alternative — CSS ne fournit aucune API pour calculer la hauteur du texte sans le rendre. L'information est verrouillée derrière le DOM, et le DOM vous fait payer pour chaque réponse.

Les développeurs ont inventé des contournements de plus en plus désespérés. Les hauteurs estimées remplacent les mesures réelles par des approximations, provoquant des sauts de contenu visibles quand l'estimation est fausse. ResizeObserver surveille les éléments pour les changements de taille, mais il se déclenche de manière asynchrone et toujours au moins une frame trop tard. IntersectionObserver suit la visibilité mais ne dit rien sur les dimensions. Content-visibility permet au navigateur de sauter le rendu des éléments hors écran, mais casse la position de défilement et l'accessibilité. Chaque contournement traite un symptôme tout en introduisant de nouveaux problèmes.

La spécification CSS Shapes, finalisée en 2014, était censée apporter l'habillage de texte façon magazine au web. Elle permet au texte de couler autour d'une forme définie — un cercle, une ellipse, un polygone, même un canal alpha d'image. Sur le papier, c'était la réponse. En pratique, c'est remarquablement limité. CSS Shapes ne fonctionne qu'avec des éléments flottants. Le texte ne peut s'habiller que d'un seul côté de la forme. La forme doit être définie statiquement en CSS — vous ne pouvez pas l'animer ni la changer dynamiquement sans déclencher un reflow complet de la mise en page. Et parce que cela opère au sein du moteur de mise en page du navigateur, vous n'avez pas accès à la géométrie des lignes résultantes. Vous ne pouvez pas déterminer où chaque ligne de texte commence et finit, combien de lignes ont été générées, ni quelle est la hauteur totale du bloc de texte façonné.

Les mises en page éditoriales que nous voyons dans les magazines imprimés — le texte coulant autour de photographies, les citations interrompant la colonne, les colonnes multiples avec un passage de texte fluide — sont restées hors de portée pour le web. Non pas parce qu'elles sont conceptuellement difficiles, mais parce que le coût en performance de leur implémentation avec la mesure DOM les rend impraticables. Une mise en page éditoriale à deux colonnes qui redistribue le texte autour de trois formes d'obstacle nécessite de mesurer et positionner des centaines de lignes de texte. À trente millisecondes par mesure, cela prendrait des secondes — une éternité pour une frame de rendu.

Et si la mesure de texte ne nécessitait pas du tout le DOM\u202F? Et si vous pouviez calculer exactement où chaque ligne de texte se couperait, exactement quelle serait la largeur de chaque ligne, et exactement quelle serait la hauteur de l'ensemble du bloc de texte, en n'utilisant rien d'autre que de l'arithmétique\u202F?

C'est l'idée centrale de pretext. L'API canvas du navigateur inclut une méthode measureText qui retourne la largeur de n'importe quelle chaîne dans n'importe quelle police sans déclencher de reflow de mise en page. La mesure canvas utilise le même moteur de police que le rendu DOM — les résultats sont identiques. Mais parce qu'elle opère en dehors de l'arbre de mise en page, elle ne porte aucune pénalité de reflow.

Pretext exploite cette asymétrie. Quand le texte apparaît pour la première fois, pretext mesure chaque mot une fois via canvas et met les largeurs en cache. Après cette phase de préparation, la mise en page est de l'arithmétique pure\u202F: parcourir les largeurs en cache, suivre la largeur courante de la ligne, insérer des sauts de ligne quand la largeur dépasse le maximum, et additionner les hauteurs de ligne. Pas de DOM. Pas de reflow. Pas d'accès à l'arbre de mise en page.

L'amélioration de performance n'est pas incrémentale. Mesurer cinq cents blocs de texte avec les méthodes DOM coûte quinze à trente millisecondes et déclenche cinq cents reflows de mise en page. Avec pretext, la même opération coûte 0,05 milliseconde et déclenche zéro reflow. C'est une amélioration de trois cents à six cents fois. Mais même ce chiffre sous-estime l'impact, parce que le coût de pretext n'augmente pas avec la complexité de la page — il est indépendant du nombre d'autres éléments présents sur la page.

Avec la mesure de texte sans DOM, une classe entière d'interfaces auparavant irréalisables devient triviale. Le texte peut couler autour de formes arbitraires, non pas parce que le moteur de mise en page du navigateur le supporte, mais parce que vous contrôlez directement les largeurs de ligne. Pour chaque ligne de texte, vous calculez quels intervalles horizontaux sont bloqués par des obstacles, les soustrayez de la largeur disponible, et passez la largeur restante au moteur de mise en page. Le moteur retourne le texte qui tient, et vous positionnez la ligne au bon décalage.

C'est exactement ce que CSS Shapes essayait d'accomplir, mais sans aucune de ses limitations. Les obstacles peuvent être de n'importe quelle forme — rectangles, cercles, polygones arbitraires, même le canal alpha d'une image. Le texte s'habille des deux côtés simultanément. Les obstacles peuvent bouger, s'animer, ou être déplacés par l'utilisateur, et le texte se redistribue instantanément parce que le calcul de mise en page prend moins d'une milliseconde.

Le shrinkwrap est une autre capacité que CSS ne peut pas exprimer. Étant donné un bloc de texte multiligne, quelle est la largeur la plus étroite qui préserve le nombre actuel de lignes\u202F? CSS offre fit-content, qui fonctionne pour les lignes uniques mais laisse toujours de l'espace mort pour le texte multiligne. Pretext résout cela avec une recherche binaire sur les largeurs\u202F: rétrécir jusqu'à ce que le nombre de lignes augmente, puis reculer. Le résultat est la boîte englobante la plus serrée possible — parfaite pour les bulles de messages de chat, les légendes d'images et le texte d'infobulles.

Le rendu virtualisé de texte devient exact plutôt qu'estimé. Une liste virtuelle doit connaître la hauteur des éléments avant qu'ils n'entrent dans la fenêtre d'affichage, pour pouvoir les positionner correctement et calculer l'étendue du défilement. Sans pretext, vous devez soit rendre les éléments hors écran pour les mesurer (ce qui va à l'encontre de l'objectif de la virtualisation), soit estimer les hauteurs et accepter des sauts visuels quand les éléments entrent dans la fenêtre d'affichage avec des hauteurs différentes de celles prédites. Pretext calcule les hauteurs exactes sans créer aucun élément DOM, permettant une virtualisation parfaite avec zéro artefact visuel.

Le flux de texte multi-colonnes avec passage de curseur est peut-être la capacité la plus frappante. La colonne gauche consomme le texte jusqu'en bas, puis passe son curseur à la colonne droite. La colonne droite reprend exactement là où la colonne gauche s'est arrêtée, sans duplication, sans espace, et avec une coupure de ligne parfaite à la frontière de colonne. C'est ainsi que fonctionnent les journaux et magazines sur papier, mais cela n'a jamais été réalisable sur le web sans des hacks extrêmes impliquant des éléments multiples, du dépassement caché, et un découpage de contenu géré en JavaScript.

Pretext rend cela trivial. Appelez layoutNextLine en boucle pour la première colonne, en utilisant la largeur de colonne. Quand la colonne est pleine, prenez le curseur retourné et commencez une nouvelle boucle pour la seconde colonne. Le curseur porte la position exacte dans le texte préparé — quel segment, quel graphème dans ce segment. La seconde colonne continue de manière fluide depuis la première.

Le dimensionnement adaptatif des titres est un détail qui sépare la typographie professionnelle de la mise en page amateur. Le titre doit être aussi grand que possible sans couper aucun mot d'une ligne à l'autre. Cela nécessite une recherche binaire\u202F: essayer une taille de police, mesurer le texte, vérifier si des coupures de ligne se produisent à l'intérieur d'un mot, et ajuster. Avec la mesure DOM, chaque itération coûte un reflow. Avec pretext, chaque itération est une microseconde d'arithmétique.

Le reflow de texte en temps réel autour d'obstacles animés est le test de résistance ultime. La démonstration que vous êtes en train de lire rend du texte qui coule autour de plusieurs objets en mouvement simultanément, à chaque frame, à soixante frames par seconde. À chaque frame, le moteur de mise en page calcule les intersections d'obstacles pour chaque ligne de texte, détermine les emplacements horizontaux disponibles, met en page chaque ligne à la largeur et position correctes, et met à jour le DOM avec les résultats. Le temps de calcul total est généralement inférieur à une demi-milliseconde.

Les orbes lumineux qui dérivent sur cette page ne sont pas décoratifs — ils sont la démonstration. Chaque orbe est un obstacle circulaire. Pour chaque ligne de texte, le moteur vérifie si la bande verticale de la ligne intersecte chaque orbe. Si c'est le cas, il calcule l'intervalle horizontal bloqué et le soustrait de la largeur disponible. La largeur restante peut être divisée en deux segments ou plus — et le moteur remplit chaque emplacement viable, faisant couler le texte des deux côtés de l'obstacle simultanément. C'est quelque chose que CSS Shapes ne peut absolument pas faire.

Tout cela fonctionne sans une seule mesure DOM. Les positions, largeurs et contenus des lignes sont calculés entièrement en JavaScript en utilisant des métriques de police en cache. Les seules écritures DOM consistent à définir les propriétés left, top et textContent de chaque élément de ligne — le minimum absolu requis pour afficher du texte à l'écran. Le navigateur n'a jamais besoin de calculer la mise en page parce que tout le positionnement est explicite.

Cette caractéristique de performance a des implications profondes pour la plateforme web. Pendant trente ans, le navigateur a été le gardien de l'information textuelle. Si vous vouliez savoir quoi que ce soit sur la façon dont le texte allait se rendre — sa largeur, sa hauteur, où ses lignes se coupent — vous deviez demander au navigateur, et le navigateur vous faisait payer la réponse avec un reflow de mise en page. Cela créait une rareté artificielle de l'information textuelle qui contraignait ce que les interfaces pouvaient faire.

Pretext supprime cette contrainte. L'information textuelle devient abondante et bon marché. Vous pouvez demander à quoi le texte ressemblerait à mille largeurs différentes dans le temps qu'il fallait auparavant pour en demander une seule. Vous pouvez recalculer la mise en page du texte à chaque frame, à chaque événement de glissement, à chaque pixel de redimensionnement de fenêtre, sans aucun souci de performance.

Les implications s'étendent au-delà de la mise en page vers la composition. Quand vous avez une mesure de texte instantanée, vous pouvez construire des moteurs de composition qui combinent texte, graphiques, animation et interaction d'une manière qui était auparavant réservée aux moteurs de jeu et aux applications natives. Le texte devient un participant de premier plan dans la composition visuelle, pas un bloc statique autour duquel le reste de l'interface doit travailler.

Imaginez une visualisation de données où les étiquettes se redistribuent autour des éléments du graphique à mesure que l'utilisateur zoome et déplace la vue. Imaginez un éditeur de documents collaboratif où le texte coule autour de widgets intégrés, d'images et d'annotations placées par d'autres utilisateurs, se mettant à jour en direct quand ils déplacent les choses. Imaginez une application de cartographie où les noms de lieux s'habillent intelligemment autour des caractéristiques géographiques au lieu de les chevaucher. Ce ne sont pas des hypothèses — ce sont des problèmes d'ingénierie qui deviennent résolubles quand la mesure de texte coûte une microseconde au lieu de trente millisecondes.

Le web ouvert mérite une typographie à la hauteur de ses ambitions. Nous construisons des applications qui rivalisent avec les logiciels natifs dans toutes les dimensions sauf le texte. Nos animations sont fluides, nos interactions sont réactives, nos graphiques sont époustouflants — mais notre texte reste dans des boîtes rigides, incapable de couler autour d'obstacles, incapable de s'adapter à des mises en page dynamiques, incapable de participer aux compositions fluides qui définissent le design d'interface moderne.

C'est ce qui change quand la mesure de texte devient gratuite. Pas légèrement meilleur — catégoriquement différent. Les interfaces trop coûteuses à construire deviennent triviales. Les mises en page qui n'existaient qu'en impression deviennent interactives. Le texte qui restait dans des boîtes commence à couler.

Le web attend cela depuis trente ans. Une bibliothèque de quinze kilo-octets sans aucune dépendance le fournit. Aucun changement d'API de navigateur nécessaire. Aucun processus de spécification. Aucun calendrier de standardisation pluriannuel. Juste des mathématiques, des mesures en cache, et l'audace de demander\u202F: et si nous arrêtions simplement de demander au DOM\u202F?

Quinze kilo-octets. Zéro dépendance. Zéro lecture DOM. Et le texte coule.`

export const PULLQUOTE_TEXTS = [
  '«\u202FL\u2019amélioration de performance n\u2019est pas incrémentale — elle est catégorique. 0,05\u202Fms contre 30\u202Fms. Zéro reflow contre cinq cents.\u202F»',
  '«\u202FLe texte devient un participant de premier plan dans la composition visuelle — pas un bloc statique, mais un matériau fluide qui s\u2019adapte en temps réel.\u202F»',
]
